# Generated by Django 3.1.2 on 2020-11-14 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigh_number', models.SmallIntegerField(default=0)),
                ('parse_text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=main_app.models.doc_file_path)),
                ('user', models.ForeignKey(blank=True, default='no_user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
