# Generated by Django 3.1.2 on 2020-11-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_documents_req_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='req_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
