# Generated by Django 3.1.3 on 2020-11-16 08:14

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201114_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='image',
            field=models.FileField(upload_to=main_app.models.doc_file_path),
        ),
    ]
