# Generated by Django 3.1.3 on 2020-11-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_documents_sig_in_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='sig_in_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
