# Generated by Django 3.1.3 on 2020-11-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_historicalpoll_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpoll',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='HistoricalPoll',
        ),
    ]
